### PR TITLE
fix(resolveBin): windows will resolve to .cmd binaries if available (#8)

### LINKED ISSUE #8: Fix resolveBin for windows
`resolveBin`: https://github.com/kentcdodds/kcd-scripts/blob/bd3d6425598db7f25ee15f14238739abf5b28178/src/utils.js#L21-L44

It's responsible for taking a module name (like `eslint`) and getting a path to the executable binary. If the path to the executable is the same as the one that's in the `$PATH` environment variable (using `which`), then we can return the raw binary name itself and execute a script with that, otherwise we'll return the full path so it's executed with the full path (because it's not available in `$PATH` presumably.

This is useful because if the user sees the script we run (which they do in some situations) then the script will be shorter.

It works on linux systems right now, but apparently the result of `which.sync` is to a file ending in `.CMD` and isn't a symlink (so the `realpathSync` doesn't resolve it to the binary path).

So we need to find a package that will do this for us (I already tried [`resolve-bin`](https://www.npmjs.com/package/resolve-bin) and it didn't work the way I want it to) or fix this function up to make it work for windows as well as linux.

Anyone wanna help out?

### PR DESCRIPTION
**Pull request by adamdharrington**
**What**: fixes #8

**Why**: Developers using windows could not run build using the --bundle flag because of the way windows resolves bins. This was blocking some devs on my team from adopting kcd-scripts.

**How**: by returning early when pathFromWhich resolves a .cmd file (only happens on windows environments)

**Checklist**:

- [ ] Documentation N/A
- [x ] Tests
- [x ] Ready to be merged

### CODE REVIEW

File: src/__tests__/utils.js [hunk 1]
```diff
@@ -51,6 +51,25 @@ test(`resolveBin resolves to the binary if it's in $PATH`, () => {
   expect(whichSyncMock).toHaveBeenCalledWith('cross-env')
 })
 
+describe('for windows', () => {
+  let realpathSync
```
Comment (adamdharrington) [inline src/__tests__/utils.js]: Describe block used so we don't need to mock fs for other tests that rely on real fs

**Comment by kentcdodds** [comment]
Thanks!

@allcontributors[bot] please add @adamdharrington for code and tests
