### PR TITLE
Fix/locate all prettier configs

### LINKED ISSUE #96: `format` does not recognize all `prettier` config formats.
- `kcd-scripts` version: 1.8.0
- `node` version: 10.16.3
- `npm` (or `yarn`) version: 6.11.3

Relevant code or config

```
# .prettierrc.toml
semi = true
singleQuote = false
```

What you did:

Added a local `.prettierrc.toml` and ran format.

What happened:

The local configuration was not respected.

[Reproduction repository](https://github.com/schaab/kcd-scripts-prettier-config)

Problem description: I have a local `.prettierrc.toml` and it is not being respected.

Suggested solution: Prettier uses `cosmiconfig` for configuration file support. Leverage cosmiconfig when looking for local configuration. It also handles inspecting `package.json` as well. I suspect you could leverage this with all the different commands eliminating the need to do the search yourself.

### PR DESCRIPTION
**Pull request by schaab**
Fixes #96 

**What**:

The `format` command does not recognize all local configuration file types

**Why**:

The docs state that the tool will respect a local configuration for a tool and use that over the default.

**How**:

Leverage `cosmiconfig` to search for any type of local configuration. `Prettier` uses it for config file support. This allows us to look for a module name rather than maintaining a list of files types to look for.

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -168,12 +169,20 @@ function writeExtraEntry(name, {cjs, esm}, clean = true) {
   )
 }
 
+function hasLocalConfig(moduleName, searchOptions = {}) {
```
Comment (kentcdodds) [inline src/utils.js]: doesn't prettier have a function for finding config? Maybe we should use that instead?

Comment (schaab) [reply src/utils.js]: Yes, it does. 

I was thinking that this eventually this could be used for the other commands as well.

**Comment by kentcdodds** [comment]
@all-contributors please add @schaab for code and tests
